[project]
name = "sae-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.13" 
dependencies = [
    "accelerate>=0.30.0",
    "datasets>=2.19.1",
    "hf-transfer>=0.1.9",
    "pyarrow<21.0.0",
    "tensorboard>=2.21.0",
    "tensorboardx>=2.6.5",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "tqdm>=4.68.3",
    "transformers>=4.55.0",
    "vllm>=0.17.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["experiments*"]